### ISSUE TITLE
GitHub Pages로 배포하는 것은 어떨까요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-1-MagicalLas#25]
간단하게 정적 사이트로 GitHub Pages로 배포하면 쉽게 배포할 수 있을 것 같습니다. 다른 방법으로 고민하고 계신게 있으실까요?

**Comment by MagicalLas** [comment]
https://github.com/CodeSoom/project-spring-1-MagicalLas/issues/1#issuecomment-812837600 에서 이미 배포를 생각하였고, 지금도 배포되고 있어요.

**Comment by MagicalLas** [comment]
atmop.dev 로 들어오시면 라이브중인 서비스를 이용하실 수 있습니다!

**Comment by MagicalLas** [comment]
https://github.com/CodeSoom/project-spring-1-MagicalLas/blob/main/deploy.sh 배포 커맨드로 배포도 어느정도 자동화를 해두었어요.
이 상태에서 깃헙 페이지로 옮기는 것과 그냥 두는 것을 생각한다면 그대로 두는게 좋을 것 같네요.
깃헙 페이지를 쓰면 좋은 점이 있을까요?

**Comment by hannut91** [comment]
아하 ㅎㅎ 저는 API만 배포된줄 알았어요. 깃헙페이지를 사용하면 그냥 무료이고 도메인도 저희가 지원해드릴 수 있어서 말씀드려보았습니다!

**Comment by hannut91** [comment]
배포가 되었으므로 닫습니다!
